POST http://localhost:3000/auth/signup HTTP/1.1
content-type: application/json

{
  "name": "test",
  "password": "test",
  "passwordConfirmation": "test",
  "email": "vitor1020@email.com.br",
  "role": "user"
}
#####

POST http://localhost:3000/auth/login HTTP/1.1
content-type: application/json

{
  "password": "test",
  "email": "vitor1020@email.com.br"
}

####
GET http://localhost:3000/users/email/vitor1020@email.com.br
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoidGVzdCIsImVtYWlsIjoidml0b3IxMDIwQGVtYWlsLmNvbS5iciIsImlhdCI6MTYzNjEzNDEyMSwiZXhwIjoxNjM2MTM3NzIxfQ.EuGacrOplPlwbbNscguUksfHd_EHiTeG6rvTmyVm75w

